In [10]:
import pandas as pd
import numpy as np

In [11]:
#Positives Data Inspection
positives = pd.read_csv("../processed_data/positives.csv",  parse_dates=["DATETIME"])

positives = positives[
    [
        'DATETIME',
        'LAT',
        'LON',
        'DISTRICT',
        'TEMPERATURE',
        'PERCIPITATION',
        'WIND SPEED',
        'RAIN',
        'SNOWFALL',
        'CRIME HAPPENED',
    ]
]
positives.head()

positives.head()

,DATETIME,LAT,LON,DISTRICT,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL,CRIME HAPPENED
0,2010-02-20 13:00:00,33.9825,-118.2695,9,14.2,0.0,9.7,0.0,0.0,1
1,2010-09-12 00:00:00,33.9599,-118.3962,11,16.5,0.0,4.1,0.0,0.0,1
2,2010-08-09 15:00:00,34.0224,-118.2524,9,25.5,0.0,11.5,0.0,0.0,1
3,2010-01-05 01:00:00,34.1016,-118.3295,13,8.1,0.0,7.4,0.0,0.0,1
4,2010-01-02 21:00:00,34.0387,-118.2488,14,11.6,0.0,8.5,0.0,0.0,1

In [12]:
#Negatives Data Inspection
negatives = pd.read_csv("../processed_data/negatives.csv",  parse_dates=["DATETIME"])

negatives = negatives[
    [
        'DATETIME',
        'LAT',
        'LON',
        'DISTRICT',
        'TEMPERATURE',
        'PERCIPITATION',
        'WIND SPEED',
        'RAIN',
        'SNOWFALL',
        'CRIME HAPPENED',
    ]
]

negatives.head()

,DATETIME,LAT,LON,DISTRICT,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL,CRIME HAPPENED
0,2010-02-20 22:00:00,33.971657,-118.313224,8,11.2,0.0,3.9,0.0,0.0,0
1,2010-09-12 12:00:00,34.074193,-118.460474,5,27.0,0.0,11.3,0.0,0.0,0
2,2010-08-09 17:00:00,34.009022,-118.323385,10,24.2,0.0,8.7,0.0,0.0,0
3,2010-01-05 16:00:00,34.049717,-118.413323,5,20.2,0.0,9.1,0.0,0.0,0
4,2010-01-02 11:00:00,34.236798,-118.581298,12,19.1,0.0,8.8,0.0,0.0,0

In [14]:
# Combine datasets
dataset = pd.concat(
    [positives, negatives],
    ignore_index=True
)

In [15]:
# Shuffle
dataset = dataset.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [16]:
dataset.isna().sum()

DATETIME          0
LAT               0
LON               0
DISTRICT          0
TEMPERATURE       0
PERCIPITATION     0
WIND SPEED        0
RAIN              0
SNOWFALL          0
CRIME HAPPENED    0
dtype: int64

In [17]:
dataset['CRIME HAPPENED'].value_counts()

CRIME HAPPENED
1    207693
0    207656
Name: count, dtype: int64

In [18]:
dataset.head()

,DATETIME,LAT,LON,DISTRICT,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL,CRIME HAPPENED
0,2010-12-20 18:00:00,33.931400,-118.416000,11,13.8,3.7,9.0,3.7,0.0,1
1,2010-10-02 19:00:00,34.050997,-118.412765,5,20.7,0.0,6.0,0.0,0.0,0
2,2010-03-19 04:00:00,34.296594,-118.489569,12,8.5,0.0,5.4,0.0,0.0,0
3,2010-07-26 19:00:00,34.157700,-118.390000,2,20.5,0.0,6.4,0.0,0.0,1
4,2010-06-01 14:00:00,34.115603,-118.409527,5,19.8,0.0,10.2,0.0,0.0,0

In [19]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415349 entries, 0 to 415348
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DATETIME        415349 non-null  datetime64[ns]
 1   LAT             415349 non-null  float64
 2   LON             415349 non-null  float64
 3   DISTRICT        415349 non-null  int64
 4   TEMPERATURE     415349 non-null  float64
 5   PERCIPITATION   415349 non-null  float64
 6   WIND SPEED      415349 non-null  float64
 7   RAIN            415349 non-null  float64
 8   SNOWFALL        415349 non-null  float64
 9   CRIME HAPPENED  415349 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(2)
memory usage: 31.7 MB

In [20]:
# Change datetime data to be able to train model - datatime separate to columns
dataset['YEAR'] = dataset['DATETIME'].dt.year
dataset['MONTH'] = dataset['DATETIME'].dt.month
dataset['DAY'] = dataset['DATETIME'].dt.day
dataset['DAY OF WEEK'] = dataset['DATETIME'].dt.dayofweek
dataset['HOUR'] = dataset['DATETIME'].dt.hour
dataset = dataset.drop(columns=['DATETIME'])

In [21]:
dataset.head()

,LAT,LON,DISTRICT,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL,CRIME HAPPENED,YEAR,MONTH,DAY,DAY OF WEEK,HOUR
0,33.931400,-118.416000,11,13.8,3.7,9.0,3.7,0.0,1,2010,12,20,0,18
1,34.050997,-118.412765,5,20.7,0.0,6.0,0.0,0.0,0,2010,10,2,5,19
2,34.296594,-118.489569,12,8.5,0.0,5.4,0.0,0.0,0,2010,3,19,4,4
3,34.157700,-118.390000,2,20.5,0.0,6.4,0.0,0.0,1,2010,7,26,0,19
4,34.115603,-118.409527,5,19.8,0.0,10.2,0.0,0.0,0,2010,6,1,1,14

In [22]:
# Convert latitude/longitude (in degrees) to 3D Cartesian coordinates (X, Y, Z)
R = 6371 # Earth radius in km

lat_rad = np.radians(dataset['LAT'])
lon_rad = np.radians(dataset['LON'])

dataset['X'] = R * np.cos(lat_rad) * np.cos(lon_rad)
dataset['Y'] = R * np.cos(lat_rad) * np.sin(lon_rad)
dataset['Z'] = R * np.sin(lat_rad)

dataset.drop(columns=['LAT', 'LON'], inplace=True)

In [12]:
dataset.head()

,DISTRICT,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL,CRIME HAPPENED,YEAR,MONTH,DAY,DAY OF WEEK,HOUR,X,Y,Z
0,7,11.4,0.0,6.5,0.0,0.0,1,2010,12,21,1,17,-2509.562849,-4630.149776,3585.170618
1,15,25.6,0.0,10.2,0.0,0.0,1,2010,7,1,3,17,-2502.035656,-4656.300394,3556.448400
2,6,16.5,0.0,3.5,0.0,0.0,0,2010,8,13,4,5,-2510.939314,-4633.891910,3579.367337
3,4,8.4,0.0,4.7,0.0,0.0,0,2010,2,9,1,8,-2503.184699,-4640.929534,3575.679016
4,5,25.1,0.0,5.2,0.0,0.0,1,2010,9,28,1,20,-2508.271802,-4643.115206,3569.270898

In [23]:
from sklearn.preprocessing import OneHotEncoder

# Use one-hot encoding to convert district categories into separate binary features
encoder = OneHotEncoder(drop='first', sparse_output=False)

district_encoded = encoder.fit_transform(dataset[['DISTRICT']])

# Convert to DataFrame
district_df = pd.DataFrame(
    district_encoded,
    columns=encoder.get_feature_names_out(['DISTRICT'])
)

# Drop original column and concatenate
dataset = pd.concat([dataset.drop(columns=['DISTRICT']), district_df], axis=1)

In [24]:
import numpy as np

# Encode cyclical time features (hour, month, day of week, and day of month) using sine/cosine 
# transformations to preserve their circular nature (23h is close to 0h, 31st day close to 1st)

# Hour
dataset["HOUR_sin"] = np.sin(2 * np.pi * dataset["HOUR"] / 24)
dataset["HOUR_cos"] = np.cos(2 * np.pi * dataset["HOUR"] / 24)

# Month
dataset["MONTH_sin"] = np.sin(2 * np.pi * dataset["MONTH"] / 12)
dataset["MONTH_cos"] = np.cos(2 * np.pi * dataset["MONTH"] / 12)

#Day
dataset["DAY_sin"] = np.sin(2 * np.pi * dataset["DAY"] / 31)
dataset["DAY_cos"] = np.cos(2 * np.pi * dataset["DAY"] / 31)

# Day of week
dataset["DOW_sin"] = np.sin(2 * np.pi * dataset["DAY OF WEEK"] / 7)
dataset["DOW_cos"] = np.cos(2 * np.pi * dataset["DAY OF WEEK"] / 7)

# Drop originals
dataset = dataset.drop(columns=["HOUR", "MONTH", "DAY", "DAY OF WEEK"])

In [25]:
dataset.head()

,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL,CRIME HAPPENED,YEAR,X,Y,Z,...,DISTRICT_14,DISTRICT_15,HOUR_sin,HOUR_cos,MONTH_sin,MONTH_cos,DAY_sin,DAY_cos,DOW_sin,DOW_cos
0,13.8,3.7,9.0,3.7,0.0,1,2010,-2515.476544,-4649.172947,3556.291561,...,0.0,0.0,-1.000000,-1.836970e-16,-2.449294e-16,1.000000e+00,-0.790776,-0.612106,0.000000,1.000000
1,20.7,0.0,6.0,0.0,0.0,0,2010,-2511.676421,-4642.775770,3567.317719,...,0.0,0.0,-0.965926,2.588190e-01,-8.660254e-01,5.000000e-01,0.394356,0.918958,-0.974928,-0.222521
2,8.5,0.0,5.4,0.0,0.0,0,2010,-2510.580691,-4625.922636,3589.911609,...,0.0,0.0,0.866025,5.000000e-01,1.000000e+00,6.123234e-17,-0.651372,-0.758758,-0.433884,-0.900969
3,20.5,0.0,6.4,0.0,0.0,1,2010,-2506.668408,-4637.920817,3577.142014,...,0.0,0.0,-0.965926,2.588190e-01,-5.000000e-01,-8.660254e-01,-0.848644,0.528964,0.000000,1.000000
4,19.8,0.0,10.2,0.0,0.0,0,2010,-2509.498695,-4639.376732,3573.267530,...,0.0,0.0,-0.500000,-8.660254e-01,1.224647e-16,-1.000000e+00,0.201299,0.979530,0.781831,0.623490

In [26]:
from sklearn.preprocessing import StandardScaler

# Standardize numerical features to ensure all values are on a similar scale
scaler = StandardScaler()
cols_to_scale = ["TEMPERATURE", "WIND SPEED", "RAIN", "SNOWFALL", "X", "Y", "Z"]
dataset[cols_to_scale] = scaler.fit_transform(dataset[cols_to_scale])

In [27]:
# Compute the correlation between numerical features to see how strongly they are linearly related
dataset[["PERCIPITATION", "RAIN"]].corr()

               PERCIPITATION  RAIN
PERCIPITATION            1.0   1.0
RAIN                     1.0   1.0

In [28]:
dataset = dataset.drop(columns=["RAIN"])

In [29]:
(dataset['SNOWFALL'] != 0).sum()

0

In [30]:
dataset = dataset.drop(columns=["SNOWFALL"])

In [31]:
dataset.head()

,TEMPERATURE,PERCIPITATION,WIND SPEED,CRIME HAPPENED,YEAR,X,Y,Z,DISTRICT_2,DISTRICT_3,...,DISTRICT_14,DISTRICT_15,HOUR_sin,HOUR_cos,MONTH_sin,MONTH_cos,DAY_sin,DAY_cos,DOW_sin,DOW_cos
0,-0.494332,3.7,0.472165,1,2010,-0.940184,-0.748185,-1.337136,0.0,0.0,...,0.0,0.0,-1.000000,-1.836970e-16,-2.449294e-16,1.000000e+00,-0.790776,-0.612106,0.000000,1.000000
1,0.535942,0.0,-0.278407,0,2010,-0.464868,-0.140105,-0.386732,0.0,0.0,...,0.0,0.0,-0.965926,2.588190e-01,-8.660254e-01,5.000000e-01,0.394356,0.918958,-0.974928,-0.222521
2,-1.285702,0.0,-0.428521,0,2010,-0.327815,1.461858,1.560758,0.0,0.0,...,0.0,0.0,0.866025,5.000000e-01,1.000000e+00,6.123234e-17,-0.651372,-0.758758,-0.433884,-0.900969
3,0.506079,0.0,-0.178330,1,2010,0.161530,0.321379,0.460077,1.0,0.0,...,0.0,0.0,-0.965926,2.588190e-01,-5.000000e-01,-8.660254e-01,-0.848644,0.528964,0.000000,1.000000
4,0.401558,0.0,0.772394,0,2010,-0.192480,0.182988,0.126115,0.0,0.0,...,0.0,0.0,-0.500000,-8.660254e-01,1.224647e-16,-1.000000e+00,0.201299,0.979530,0.781831,0.623490

In [32]:
dataset.columns = dataset.columns.str.replace(' ', '_')

In [33]:
dataset.head()

,TEMPERATURE,PERCIPITATION,WIND_SPEED,CRIME_HAPPENED,YEAR,X,Y,Z,DISTRICT_2,DISTRICT_3,...,DISTRICT_14,DISTRICT_15,HOUR_sin,HOUR_cos,MONTH_sin,MONTH_cos,DAY_sin,DAY_cos,DOW_sin,DOW_cos
0,-0.494332,3.7,0.472165,1,2010,-0.940184,-0.748185,-1.337136,0.0,0.0,...,0.0,0.0,-1.000000,-1.836970e-16,-2.449294e-16,1.000000e+00,-0.790776,-0.612106,0.000000,1.000000
1,0.535942,0.0,-0.278407,0,2010,-0.464868,-0.140105,-0.386732,0.0,0.0,...,0.0,0.0,-0.965926,2.588190e-01,-8.660254e-01,5.000000e-01,0.394356,0.918958,-0.974928,-0.222521
2,-1.285702,0.0,-0.428521,0,2010,-0.327815,1.461858,1.560758,0.0,0.0,...,0.0,0.0,0.866025,5.000000e-01,1.000000e+00,6.123234e-17,-0.651372,-0.758758,-0.433884,-0.900969
3,0.506079,0.0,-0.178330,1,2010,0.161530,0.321379,0.460077,1.0,0.0,...,0.0,0.0,-0.965926,2.588190e-01,-5.000000e-01,-8.660254e-01,-0.848644,0.528964,0.000000,1.000000
4,0.401558,0.0,0.772394,0,2010,-0.192480,0.182988,0.126115,0.0,0.0,...,0.0,0.0,-0.500000,-8.660254e-01,1.224647e-16,-1.000000e+00,0.201299,0.979530,0.781831,0.623490

In [34]:
# Export the processed DataFrame to CSV
dataset.to_csv("../processed_data/ml_dataset.csv", index=False)